version: 0.1


phases:
  install:
    commands:
      # - command
      # - command
    finally:
      # - command
      # - command
  pre_build:
    commands:
      npm run test
    finally:
      # - command
      # - command
  build:
    commands:
      npm run build
      # - command
    finally:
      # - command
      # - command
  post_build:
    commands:
      # - command
      # - command
    finally:
      # - command
      # - command